### ISSUE TITLE
Create a more efficient way of importing struct data

### ISSUE THREAD

**Issue by nickbeckwith** [vkottler/badgerloopControls#1]
Right now, adding a new sensor is kind of cumbersome. Need a way to import sensor characteristics (name, type, pin1, pin2) without writing the below every time.

`sensors[0]   =   (struct Sensor){"THERMISTOR 1", THERMISTOR, pin1, pin2};`

Would be great if we could read off of a .txt file and initialize all the sensors in a for loop.

**Comment by shanemmattner** [comment]
Perhaps this might work:

https://www.codingunit.com/c-tutorial-file-io-using-text-files

**Comment by vkottler** [comment]
Are we still going to compare two different pins for the thermistor readings? I think we have switched from wheatstone bridge to regular voltage divider with one reading compared with the ground reference.

Also, although the XC32 compiler does have a stdio.h that declares the same C functions available to us on AMD64/x86 from gcc, consider the lifespan of any custom File struct that lives on SRAM (I don't think we can or should write to flash during runtime). Most certainly we will need to interface with long-term storage such as an SD card using SPI and one of these breakout boards: https://www.sparkfun.com/products/544
