### ISSUE TITLE
Seemingly unresponsive LEDS

### ISSUE THREAD

**Issue by nickbeckwith** [vkottler/badgerloopControls#3]
Can you look at the commits to the CAN testing? LEDs are not turning on when they should as if they aren't entering the transmitter/receiver loops.

**Comment by vkottler** [comment]
The problem is CAN_init() hard codes the Max32's SID to the one that the kelly controller sends out (see line 20 in CAN.c).

Easiest fix is to pass SID as an argument to CAN_init. For our purpose, it needs to be based on the board number and there should be a function for that in utils.c

**Comment by vkottler** [comment]
Also keep in mind that when you set an SID to a certain value, which corresponds to a specific bit pattern, hardware filters come in to play. I'm not an expert on how the filters work but essentially if a bit is set in the filter, the hardware will check if the SID bit from the message matches the software SID bit and if it doesn't it will ignore the message. You can set up the module to listen to every message, though
